all:
	gcc sort.c -o sort -std=c99

run:
	./sort -std=c99

clean:
	rm sort

#Description: program "sort.c" reads in a list of student names from the keyboard and displays them in alphabetical order on the screen. Assume the sequence is read until an EOF is encountered. 

#Commands: 
	
#	all: Used to compiles sort.c into an executable named sort using gcc
#	run: target run the compiled program 
#	clean: clean and remove sort executable


# HOW TO RUN
# type the commands "make", "make run", after you run clean the exe with "make clean"
